# Generated by Django 2.2.5 on 2019-11-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangoAPI', '0003_auto_20191106_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('designprojecttbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                              parent_link=True, primary_key=True, serialize=False, to='djangoAPI.DesignProjectTbl')),
                ('bus_unit_name', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=200)),
                ('project_manager_email', models.EmailField(max_length=254)),
                ('key_bus_unit_contract', models.CharField(max_length=200)),
                ('key_bus_unit_contract_email', models.EmailField(max_length=254)),
                ('asset_data_steward', models.CharField(max_length=200)),
                ('asset_data_steward_email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'project_projectdetails',
            },
            bases=('djangoAPI.designprojecttbl',),
        ),
        migrations.CreateModel(
            name='ProjectPhases',
            fields=[
                ('constructionphasetbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                                  parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ConstructionPhaseTbl')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'project_projectphases',
            },
            bases=('djangoAPI.constructionphasetbl',),
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('user_role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'project_userprojects',
            },
        ),
    ]
