# Generated by Django 2.2.5 on 2019-11-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0003_auto_20191106_1345'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPhases',
            new_name='ConstructionPhases',
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='bus_unit_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoAPI.DesignProjectHumanRoleTypeTbl'),
        ),
        migrations.AlterModelTable(
            name='constructionphases',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projectdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprojects',
            table=None,
        ),
    ]
