# Generated by Django 2.2.5 on 2019-11-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191121_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='bus_unit_name',
            new_name='business_unit_name',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='key_bus_unit_contract',
            new_name='key_bus_unit_contact',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='key_bus_unit_contract_email',
            new_name='key_bus_unit_contact_email',
        ),
    ]
