# Generated by Django 2.2.5 on 2019-09-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newProjectAssetRoleTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.projectAssetRoleRecordTbl')),
                ('new_role', models.BooleanField()),
            ],
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.RenameField(
            model_name='projectassetrolerecordtbl',
            old_name='role_spatial_side_id',
            new_name='role_spatial_site_id',
        ),
        migrations.AlterField(
            model_name='existingassetmovedbyprojecttbl',
            name='final_project_asset_role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRoleRecordTbl'),
        ),
        migrations.AlterField(
            model_name='predesignreconciledassetrecordtbl',
            name='initial_project_asset_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRoleRecordTbl'),
        ),
        migrations.AlterField(
            model_name='projectassetrecordtbl',
            name='project_tbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectTbl'),
        ),
        migrations.AlterField(
            model_name='projectassetrolerecordtbl',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRoleRecordTbl', verbose_name='Parent Number'),
        ),
    ]
