# Generated by Django 2.2.5 on 2019-09-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0002_auto_20190925_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassetrolerecordtbl',
            name='project_tbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectTbl'),
        ),
    ]
