# Generated by Django 2.2.5 on 2019-11-05 21:12

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_number', models.TextField(null=True)),
                ('role_name', models.TextField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
                ('role_exists', models.BooleanField(null=True)),
                ('role_missing_from_registry', models.BooleanField(null=True)),
                ('full_path', models.TextField(null=True)),
                ('parent_changed', models.BooleanField(null=True)),
                ('asset_id', models.IntegerField(null=True)),
                ('asset_serial_number', models.TextField(null=True)),
                ('asset_exists', models.BooleanField(null=True)),
                ('asset_missing_from_registry', models.BooleanField(null=True)),
                ('role_changed', models.BooleanField(null=True)),
                ('approved', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'reconciliation_view_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_number', models.TextField(null=True)),
                ('role_name', models.TextField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
                ('full_path', models.TextField(null=True)),
                ('approved', models.BooleanField(null=True)),
                ('reserved', models.BooleanField(null=True)),
                ('approval_status', models.TextField(null=True)),
                ('reservable', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'reservation_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnassignedAssetsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_serial_number', models.TextField(null=True)),
                ('asset_missing_from_registry', models.BooleanField(null=True)),
                ('project_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'unassigned_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessProfileTbl',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_AccessProfileTbl',
            },
        ),
        migrations.CreateModel(
            name='AllHumanRoleTypeTbl',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'djangoAPI_AllHumanRoleTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_BusinessUnit',
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhaseTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase_number', models.BigIntegerField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('scope_description', models.TextField()),
                ('designer_organization_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_ConstructionPhaseTbl',
            },
        ),
        migrations.CreateModel(
            name='ConstructionStageTypeTbl',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_ConstructionStageTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='DBTbls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_table_name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_DBTbls',
            },
        ),
        migrations.CreateModel(
            name='DesignerPlannedActionTypeTbl',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_DesignerPlannedActionTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='DesignProjectTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase_number', models.IntegerField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scope_description', models.TextField(blank=True, null=True)),
                ('designer_organization_name', models.CharField(max_length=50)),
                ('op_bus_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.BusinessUnit')),
            ],
            options={
                'db_table': 'djangoAPI_DesignProjectTbl',
            },
        ),
        migrations.CreateModel(
            name='DesignStageTypeTbl',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_DesignStageTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='ImportedSpatialSiteTbl',
            fields=[
                ('spatial_site_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('parent_site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ImportedSpatialSiteTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ImportedSpatialSiteTbl',
            },
        ),
        migrations.CreateModel(
            name='MasterRoleNumbersTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_number', models.CharField(max_length=25, unique=True)),
                ('project_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignProjectTbl')),
            ],
            options={
                'db_table': 'djangoAPI_MasterRoleNumbersTbl',
            },
        ),
        migrations.CreateModel(
            name='RoleCriticality',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_RoleCriticality',
            },
        ),
        migrations.CreateModel(
            name='RolePriority',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_RolePriority',
            },
        ),
        migrations.CreateModel(
            name='SuperDesignProjectTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'djangoAPI_SuperDesignProjectTbl',
            },
        ),
        migrations.CreateModel(
            name='UserGroupNameTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('within_city', models.BooleanField()),
                ('with_toronto_water', models.BooleanField()),
                ('outside_organization_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_UserGroupNameTbl',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'djangoAPI_UserRole',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tw_employee', models.BooleanField()),
                ('city_employee', models.BooleanField()),
            ],
            options={
                'db_table': 'djangoAPI_UserType',
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhaseHumanRoleTypeTbl',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='djangoAPI.AllHumanRoleTypeTbl')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_ConstructionPhaseHumanRoleTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='DesignProjectHumanRoleTypeTbl',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='djangoAPI.AllHumanRoleTypeTbl')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_DesignProjectHumanRoleTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='SystemHumanRoleTypeTbl',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='djangoAPI.AllHumanRoleTypeTbl')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djangoAPI_SystemHumanRoleTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.UserGroupNameTbl')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.SystemHumanRoleTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_UserTbl',
            },
        ),
        migrations.CreateModel(
            name='UserProjectLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.DesignProjectTbl')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.UserRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.UserTbl')),
            ],
            options={
                'db_table': 'djangoAPI_UserProjectLinkTbl',
            },
        ),
        migrations.CreateModel(
            name='UserAccessLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.AccessProfileTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.UserTbl')),
            ],
            options={
                'db_table': 'djangoAPI_UserAccessLinkTbl',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=400)),
                ('op_bus_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.BusinessUnit')),
            ],
            options={
                'db_table': 'djangoAPI_Sites',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssetRoleRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=400)),
                ('approved', models.BooleanField(default=False)),
                ('ltree_path', models.TextField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl', verbose_name='Parent Number')),
                ('project_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignProjectTbl')),
                ('role_criticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.RoleCriticality')),
                ('role_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.RolePriority')),
                ('role_spatial_site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ImportedSpatialSiteTbl')),
                ('updatable_role_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.MasterRoleNumbersTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectAssetRoleRecordTbl',
            },
        ),
        migrations.CreateModel(
            name='NewProjectAssetRoleTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('new_role', models.BooleanField()),
            ],
            options={
                'db_table': 'djangoAPI_NewProjectAssetRoleTbl',
            },
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.CreateModel(
            name='ProjectAssetRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('project_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignProjectTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectAssetRecordTbl',
            },
        ),
        migrations.CreateModel(
            name='DesignStageTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.DesignProjectTbl')),
                ('design_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignStageTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_DesignStageTbl',
            },
        ),
        migrations.AddField(
            model_name='designprojecttbl',
            name='super_design_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.SuperDesignProjectTbl'),
        ),
        migrations.CreateModel(
            name='ConstructionStageTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('construction_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ConstructionPhaseTbl')),
                ('construction_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ConstructionStageTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ConstructionStageTbl',
            },
        ),
        migrations.AddField(
            model_name='constructionphasetbl',
            name='design_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.DesignProjectTbl'),
        ),
        migrations.AddField(
            model_name='constructionphasetbl',
            name='op_bus_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.BusinessUnit'),
        ),
        migrations.CreateModel(
            name='ClonedAssetAndRoleInRegistryTbl',
            fields=[
                ('mtoi', models.AutoField(primary_key=True, serialize=False, verbose_name='Avantis ID')),
                ('role_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Entity Number')),
                ('role_name', models.CharField(max_length=200, verbose_name='Entity Name')),
                ('parent_role_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Parent Number')),
                ('role_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('role_criticality', models.BigIntegerField(blank=True, null=True, verbose_name='Criticality Number')),
                ('role_priority', models.BigIntegerField(blank=True, null=True, verbose_name='Priority Number')),
                ('role_equipment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipment Type')),
                ('role_classification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classification')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('suspension_id', models.BigIntegerField(blank=True, null=True)),
                ('already_reserved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='already_reserved_group', to='djangoAPI.DesignProjectTbl')),
                ('intent_to_reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_reserve_group', to='djangoAPI.DesignProjectTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ClonedAssetAndRoleInRegistryTbl',
            },
        ),
        migrations.CreateModel(
            name='AssetClassificationTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectAssetRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_AssetClassificationTbl',
            },
        ),
        migrations.CreateModel(
            name='AccessProfileDefinitionTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_to_view', models.BooleanField()),
                ('permission_to_update', models.BooleanField()),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DBTbls')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.AllHumanRoleTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_AccessProfileDefinitionTbl',
            },
        ),
        migrations.CreateModel(
            name='PreDesignReconciledRoleRecordTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('entity_exists', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('parent_changed', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ClonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignerPlannedActionTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_PreDesignReconciledRoleRecordTbl',
            },
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.CreateModel(
            name='PreDesignReconciledAssetRecordTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRecordTbl')),
                ('entity_exists', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('role_changed', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ClonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignerPlannedActionTypeTbl')),
                ('initial_project_asset_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_PreDesignReconciledAssetRecordTbl',
            },
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='ExistingAssetDisposedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.PreDesignReconciledAssetRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ExistingAssetDisposedByProjectTbl',
            },
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='ExistingAssetMovedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.PreDesignReconciledAssetRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ExistingAssetMovedByProjectTbl',
            },
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='NewAssetDeliveredByProjectTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRecordTbl')),
                ('final_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('installation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ConstructionStageTbl')),
            ],
            options={
                'db_table': 'djangoAPI_NewAssetDeliveredByProjectTbl',
            },
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='DesignProjectHumanRoleTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignProjectTbl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.UserTbl')),
                ('human_role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignProjectHumanRoleTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_DesignProjectHumanRoleTbl',
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhaseHumanRoleTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ConstructionPhaseTbl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.UserTbl')),
                ('human_role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ConstructionPhaseHumanRoleTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ConstructionPhaseHumanRoleTbl',
            },
        ),
        migrations.CreateModel(
            name='AvantisAdditions',
            fields=[
                ('clonedassetandroleinregistrytbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ClonedAssetAndRoleInRegistryTbl')),
                ('full_path', models.TextField()),
                ('linked_role_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.MasterRoleNumbersTbl')),
                ('parent_mtoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.AvantisAdditions')),
            ],
            options={
                'db_table': 'djangoAPI_AvantisAdditions',
            },
            bases=('djangoAPI.clonedassetandroleinregistrytbl',),
        ),
        migrations.AddConstraint(
            model_name='accessprofiledefinitiontbl',
            constraint=models.UniqueConstraint(fields=('db_table', 'role'), name='one_permission_for_each_table_and_role_pair'),
        ),
        migrations.AddField(
            model_name='existingassetmovedbyprojecttbl',
            name='final_project_asset_role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl'),
        ),
        migrations.AddField(
            model_name='existingassetmovedbyprojecttbl',
            name='installation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_stage', to='djangoAPI.ConstructionStageTbl'),
        ),
        migrations.AddField(
            model_name='existingassetmovedbyprojecttbl',
            name='uninstallation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uninstall_stage', to='djangoAPI.ConstructionStageTbl'),
        ),
        migrations.AddField(
            model_name='existingassetdisposedbyprojecttbl',
            name='uninstallation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ConstructionStageTbl'),
        ),
    ]
