# Generated by Django 2.2.5 on 2019-09-17 18:38

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessProfileTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='dbTbls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_table_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='designerPlannedActionTypeTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='designStageTypeTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='importedSpatialSiteTbl',
            fields=[
                ('spatialSiteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('parentSiteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.importedSpatialSiteTbl')),
            ],
        ),
        migrations.CreateModel(
            name='operationalBusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='projectConstructionPhaseTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.BigIntegerField()),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='projectTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.CharField(max_length=400)),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.operationalBusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='roleCriticality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rolePriority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=400)),
                ('tw_employee', models.BooleanField()),
                ('city_employee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='userTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=400)),
                ('organization_name', models.CharField(max_length=400)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.userType')),
            ],
        ),
        migrations.CreateModel(
            name='userProjectLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.projectTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.userTbl')),
            ],
        ),
        migrations.CreateModel(
            name='userAccessLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.accessProfileTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.userTbl')),
            ],
        ),
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=3)),
                ('site_name', models.CharField(max_length=400)),
                ('op_bus_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.operationalBusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='projectDesignPhaseTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_design_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.designStageTypeTbl')),
                ('project_tbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.projectTbl')),
            ],
        ),
        migrations.CreateModel(
            name='projectConstructionStageTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_construction_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.projectConstructionPhaseTbl')),
                ('project_construction_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.designStageTypeTbl')),
            ],
        ),
        migrations.AddField(
            model_name='projectconstructionphasetbl',
            name='project_tbl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.projectTbl'),
        ),
        migrations.CreateModel(
            name='projectAssetRoleRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatable_role_number', models.CharField(max_length=25)),
                ('role_name', models.CharField(max_length=400)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.projectAssetRoleRecordTbl', verbose_name='Parent Number')),
                ('role_criticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.roleCriticality')),
                ('role_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.rolePriority')),
                ('role_spatial_side_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.importedSpatialSiteTbl')),
            ],
        ),
        migrations.CreateModel(
            name='projectAssetRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('project_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectTbl')),
            ],
        ),
        migrations.CreateModel(
            name='clonedAssetAndRoleInRegistryTbl',
            fields=[
                ('mtnoi', models.AutoField(primary_key=True, serialize=False, verbose_name='Avantis ID')),
                ('role_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Entity Number')),
                ('role_name', models.CharField(max_length=200, verbose_name='Entity Name')),
                ('parent_role_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Parent Number')),
                ('role_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('role_criticality', models.BigIntegerField(blank=True, null=True, verbose_name='Criticality Number')),
                ('role_priority', models.BigIntegerField(blank=True, null=True, verbose_name='Priority Number')),
                ('role_equipment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipment Type')),
                ('role_classification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classification')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('suspension_id', models.BigIntegerField(blank=True, null=True)),
                ('already_reserved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='already_reserved_group', to='djangoAPI.projectTbl')),
                ('intent_to_reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_reserve_group', to='djangoAPI.projectTbl')),
                ('role_spatial_site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.importedSpatialSiteTbl')),
            ],
        ),
        migrations.CreateModel(
            name='accessProfileDefinitionTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField()),
                ('update', models.BooleanField()),
                ('add', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.dbTbls')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.accessProfileTbl')),
            ],
        ),
        migrations.CreateModel(
            name='preDesignReconciledRoleRecordTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.projectAssetRoleRecordTbl')),
                ('does_not_exist', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.clonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.designerPlannedActionTypeTbl')),
            ],
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.CreateModel(
            name='preDesignReconciledAssetRecordTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.projectAssetRecordTbl')),
                ('does_not_exist', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.clonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.designerPlannedActionTypeTbl')),
                ('initial_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRoleRecordTbl')),
            ],
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='newAssetDeliveredByProjectTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.projectAssetRecordTbl')),
                ('final_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRoleRecordTbl')),
                ('installation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectConstructionStageTbl')),
            ],
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='existingAssetMovedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.preDesignReconciledAssetRecordTbl')),
                ('final_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectAssetRecordTbl')),
                ('installation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_stage', to='djangoAPI.projectConstructionStageTbl')),
                ('uninstallation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uninstall_stage', to='djangoAPI.projectConstructionStageTbl')),
            ],
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='existingAssetDisposedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.preDesignReconciledAssetRecordTbl')),
                ('uninstallation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.projectConstructionStageTbl')),
            ],
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
    ]
