# Generated by Django 2.2.5 on 2019-10-03 15:05

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfileTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_AccessProfileTbl',
            },
        ),
        migrations.CreateModel(
            name='DBTbls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_table_name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_DBTbls',
            },
        ),
        migrations.CreateModel(
            name='DesignerPlannedActionTypeTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_DesignerPlannedActionTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='DesignStageTypeTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_DesignStageTypeTbl',
            },
        ),
        migrations.CreateModel(
            name='ImportedSpatialSiteTbl',
            fields=[
                ('spatial_site_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('parent_site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ImportedSpatialSiteTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ImportedSpatialSiteTbl',
            },
        ),
        migrations.CreateModel(
            name='OperationalBusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'djangoAPI_OperationalBusinessUnit',
            },
        ),
        migrations.CreateModel(
            name='ProjectConstructionPhaseTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.BigIntegerField()),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
            options={
                'db_table': 'djangoAPI_ProjectConstructionPhaseTbl',
            },
        ),
        migrations.CreateModel(
            name='ProjectTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.CharField(max_length=400)),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.OperationalBusinessUnit')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectTbl',
            },
        ),
        migrations.CreateModel(
            name='RoleCriticality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'djangoAPI_RoleCriticality',
            },
        ),
        migrations.CreateModel(
            name='RolePriority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'djangoAPI_RolePriority',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=400)),
                ('tw_employee', models.BooleanField()),
                ('city_employee', models.BooleanField()),
            ],
            options={
                'db_table': 'djangoAPI_UserType',
            },
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=400)),
                ('organization_name', models.CharField(max_length=400)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.UserType')),
            ],
            options={
                'db_table': 'djangoAPI_UserTbl',
            },
        ),
        migrations.CreateModel(
            name='UserProjectLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.UserTbl')),
            ],
            options={
                'db_table': 'djangoAPI_UserProjectLinkTbl',
            },
        ),
        migrations.CreateModel(
            name='UserAccessLinkTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.AccessProfileTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.UserTbl')),
            ],
            options={
                'db_table': 'djangoAPI_UserAccessLinkTbl',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=3)),
                ('site_name', models.CharField(max_length=400)),
                ('op_bus_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.OperationalBusinessUnit')),
            ],
            options={
                'db_table': 'djangoAPI_Sites',
            },
        ),
        migrations.CreateModel(
            name='ProjectDesignPhaseTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_design_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignStageTypeTbl')),
                ('project_tbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectDesignPhaseTbl',
            },
        ),
        migrations.CreateModel(
            name='ProjectConstructionStageTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('project_construction_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectConstructionPhaseTbl')),
                ('project_construction_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignStageTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectConstructionStageTbl',
            },
        ),
        migrations.AddField(
            model_name='projectconstructionphasetbl',
            name='project_tbl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectTbl'),
        ),
        migrations.CreateModel(
            name='ProjectAssetRoleRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatable_role_number', models.CharField(max_length=25)),
                ('role_name', models.CharField(max_length=400)),
                ('ltree_path', models.TextField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl', verbose_name='Parent Number')),
                ('project_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectTbl')),
                ('role_criticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.RoleCriticality')),
                ('role_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.RolePriority')),
                ('role_spatial_site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ImportedSpatialSiteTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectAssetRoleRecordTbl',
            },
        ),
        migrations.CreateModel(
            name='NewProjectAssetRoleTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('new_role', models.BooleanField()),
            ],
            options={
                'db_table': 'djangoAPI_NewProjectAssetRoleTbl',
            },
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.CreateModel(
            name='ProjectAssetRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('project_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ProjectAssetRecordTbl',
            },
        ),
        migrations.CreateModel(
            name='ClonedAssetAndRoleInRegistryTbl',
            fields=[
                ('mtoi', models.AutoField(primary_key=True, serialize=False, verbose_name='Avantis ID')),
                ('role_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Entity Number')),
                ('role_name', models.CharField(max_length=200, verbose_name='Entity Name')),
                ('parent_role_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Parent Number')),
                ('role_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('role_criticality', models.BigIntegerField(blank=True, null=True, verbose_name='Criticality Number')),
                ('role_priority', models.BigIntegerField(blank=True, null=True, verbose_name='Priority Number')),
                ('role_equipment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipment Type')),
                ('role_classification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classification')),
                ('asset_serial_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Number')),
                ('suspension_id', models.BigIntegerField(blank=True, null=True)),
                ('already_reserved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='already_reserved_group', to='djangoAPI.ProjectTbl')),
                ('intent_to_reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_reserve_group', to='djangoAPI.ProjectTbl')),
                ('role_spatial_site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ImportedSpatialSiteTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ClonedAssetAndRoleInRegistryTbl',
            },
        ),
        migrations.CreateModel(
            name='AssetClassificationTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.ProjectAssetRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_AssetClassificationTbl',
            },
        ),
        migrations.CreateModel(
            name='AccessProfileDefinitionTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField()),
                ('update', models.BooleanField()),
                ('add', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DBTbls')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoAPI.AccessProfileTbl')),
            ],
            options={
                'db_table': 'djangoAPI_AccessProfileDefinitionTbl',
            },
        ),
        migrations.CreateModel(
            name='PreDesignReconciledRoleRecordTbl',
            fields=[
                ('projectassetrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('entity_exists', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ClonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignerPlannedActionTypeTbl')),
            ],
            options={
                'db_table': 'djangoAPI_PreDesignReconciledRoleRecordTbl',
            },
            bases=('djangoAPI.projectassetrolerecordtbl',),
        ),
        migrations.CreateModel(
            name='PreDesignReconciledAssetRecordTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRecordTbl')),
                ('entity_exists', models.BooleanField()),
                ('missing_from_registry', models.BooleanField()),
                ('cloned_role_registry_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ClonedAssetAndRoleInRegistryTbl')),
                ('designer_planned_action_type_tbl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.DesignerPlannedActionTypeTbl')),
                ('initial_project_asset_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl')),
            ],
            options={
                'db_table': 'djangoAPI_PreDesignReconciledAssetRecordTbl',
            },
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='NewAssetDeliveredByProjectTbl',
            fields=[
                ('projectassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.ProjectAssetRecordTbl')),
                ('final_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('installation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectConstructionStageTbl')),
            ],
            options={
                'db_table': 'djangoAPI_NewAssetDeliveredByProjectTbl',
            },
            bases=('djangoAPI.projectassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='ExistingAssetMovedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.PreDesignReconciledAssetRecordTbl')),
                ('final_project_asset_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectAssetRoleRecordTbl')),
                ('installation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='install_stage', to='djangoAPI.ProjectConstructionStageTbl')),
                ('uninstallation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uninstall_stage', to='djangoAPI.ProjectConstructionStageTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ExistingAssetMovedByProjectTbl',
            },
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
        migrations.CreateModel(
            name='ExistingAssetDisposedByProjectTbl',
            fields=[
                ('predesignreconciledassetrecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.PreDesignReconciledAssetRecordTbl')),
                ('uninstallation_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoAPI.ProjectConstructionStageTbl')),
            ],
            options={
                'db_table': 'djangoAPI_ExistingAssetDisposedByProjectTbl',
            },
            bases=('djangoAPI.predesignreconciledassetrecordtbl',),
        ),
    ]
