# Generated by Django 2.2.5 on 2019-10-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassetrolerecordtbl',
            options={'managed': False},
        ),
    ]
