# Generated by Django 2.2.5 on 2019-10-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0002_auto_20191009_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttbl',
            old_name='project_site',
            new_name='project_op_bus_unit',
        ),
    ]
