# Generated by Django 2.2.5 on 2019-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0002_auto_20191016_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_number', models.TextField(null=True)),
                ('role_name', models.TextField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
                ('full_path', models.TextField(null=True)),
                ('approved', models.BooleanField(null=True)),
                ('reserved', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'reservation_view',
                'managed': False,
            },
        ),
    ]
