# Generated by Django 2.2.5 on 2019-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0002_auto_20191104_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrolenumberstbl',
            name='role_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
