# Generated by Django 2.2.5 on 2019-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0002_auto_20191003_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_number', models.TextField(null=True)),
                ('role_name', models.TextField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
                ('role_exists', models.BooleanField(null=True)),
                ('role_missing_from_registry', models.BooleanField(null=True)),
                ('full_path', models.TextField(null=True)),
                ('asset_id', models.IntegerField(null=True)),
                ('asset_serial_number', models.TextField(null=True)),
                ('asset_exists', models.BooleanField(null=True)),
                ('asset_missing_from_registry', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'reconciliation_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnassignedAssetsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_serial_number', models.TextField(null=True)),
            ],
            options={
                'db_table': 'unassigned_assets',
                'managed': False,
            },
        ),
    ]
