# Generated by Django 2.2.5 on 2019-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0003_reservationview'),
    ]

    operations = [
        migrations.AddField(
            model_name='predesignreconciledassetrecordtbl',
            name='role_changed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predesignreconciledrolerecordtbl',
            name='parent_changed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
