# Generated by Django 2.2.5 on 2019-10-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0003_auto_20191009_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertbl',
            name='name',
            field=models.CharField(default='default name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertbl',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
