# Generated by Django 2.2.5 on 2019-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0004_auto_20191021_1118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reconciliationview',
            table='reconciliation_view_temp',
        ),
    ]
