# Generated by Django 2.2.5 on 2019-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0004_querytypecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_number', models.TextField(null=True)),
                ('role_name', models.TextField(null=True)),
                ('approved', models.BooleanField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('project_id', models.IntegerField(null=True)),
                ('new_role', models.BooleanField(null=True)),
                ('full_path', models.TextField(null=True)),
                ('parent_changed', models.BooleanField(null=True)),
                ('asset_id', models.IntegerField(null=True)),
                ('asset_serial_number', models.TextField(null=True)),
                ('role_changed', models.BooleanField(null=True)),
                ('installation_stage_id', models.TextField(null=True)),
                ('uninstallation_stage_id', models.TextField(null=True)),
                ('new_asset', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'change_view',
                'managed': False,
            },
        ),
    ]
