# Generated by Django 2.2.5 on 2019-11-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0005_changeview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingRoleDisposedByProject',
            fields=[
                ('predesignreconciledrolerecordtbl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoAPI.PreDesignReconciledRoleRecordTbl')),
                ('disposed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'djangoAPI_ExistingRoleDisposedByProject',
            },
            bases=('djangoAPI.predesignreconciledrolerecordtbl',),
        ),
    ]
