# Generated by Django 2.2.5 on 2019-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0007_auto_20191203_1629'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unassignedassetsview',
            table='general_unassigned_asset_view',
        ),
    ]
