# Generated by Django 2.2.5 on 2019-12-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0008_auto_20191204_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetdeliveredbyprojecttbl',
            name='final_project_asset_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ProjectAssetRoleRecordTbl'),
        ),
        migrations.AlterField(
            model_name='newassetdeliveredbyprojecttbl',
            name='installation_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ConstructionStageTbl'),
        ),
    ]
