# Generated by Django 2.2.5 on 2019-12-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0009_auto_20191210_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingassetmovedbyprojecttbl',
            name='final_project_asset_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoAPI.ProjectAssetRoleRecordTbl'),
        ),
    ]
